---
title: Earnest Agency
timezone: UTC
collections:
  pitch:
    client: automation anywhere
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    author: test
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pitch
  values:
    layout: circle
    circle-1: number one
    circle-2: number two
    image:
email: michaela.brown@earnest-agency.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
permalink: pretty # /:categories/:year/:month/:day/:title/
exclude:
- _dev
- gulpfile.js
- node_modules
- package.json
