---
title: Earnest Agency
timezone: UTC
collections:
  pitch:
    title: Pitch
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: pitch
  values:
    layout: circle
    circle-1: 
    circle-2: 
    image: 
- scope:
    path: ''
    type: pitch
  values:
    layout: square
    square-1: 
    square-2: 
    image: 
email: michaela.brown@earnest-agency.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
permalink: pretty
exclude:
- _dev
- gulpfile.js
- node_modules
- package.json
